# Generated by Django 5.0.6 on 2024-05-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clients_user_alter_doctors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializations',
            name='description',
            field=models.TextField(default='Поле описания не существовало на момент добавления этого объекта.', max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='clinic.servicespecializations', verbose_name='Специализация вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
