# Generated by Django 5.1.1 on 2024-11-09 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_doctors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть в формате: '+375 (XX) XXX-XX-XX'", regex='^(8|\\+375)(\\s?)(\\(?\\d{2,3}\\)?)(\\s?)(\\d{3})([-\\s]?)(\\d{2})([-\\s]?)(\\d{2})$')], verbose_name='Телефон'),
        ),
    ]
