# Generated by Django 5.1.1 on 2024-11-09 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_doctors_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Такие номера должны быть валидными: 80291112233, 8 (029) 1112233, +375 (29) 111-22-33, +375 (29) 111 22 33. Т.е. телефон может начинаться как и с +375, так и с 8. Код оператора может быть в скобках и без, и с пробелами. Оставшиеся часть могут быть с дефисами и пробелами.', regex='^(8|\\+375)(\\s?)(\\(?\\d{2,3}\\)?)(\\s?)(\\d{3})([-\\s]?)(\\d{2})([-\\s]?)(\\d{2})$')], verbose_name='Телефон'),
        ),
    ]
