# Generated by Django 5.0.6 on 2024-05-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='Краткая информация'),
        ),
    ]
