# Generated by Django 5.1.1 on 2024-09-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='main/certificates/', verbose_name='Сертификат (HTML файл)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='main/certificates/', verbose_name='CSS файл для сертификата'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='main/logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='main/videos/', verbose_name='Видео'),
        ),
    ]
