# Generated by Django 5.1.1 on 2024-09-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companyinfo_certificate_file_companyinfo_css_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Полный текст'),
        ),
    ]
